dist:     trusty
sudo:     true

language: cpp

os:
  - linux

packages:
  - gcc-9
  - g++-9

compiler:
  - gcc
  - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

script:
  # скрипт сборки и тестирования проекта:
  - sudo apt update
  - sudo apt install gcc-9
  - export CC=gcc-9
  - export CXX=g++-9
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .