dist:     Bionic
sudo:     true

language: cpp

os:
  - linux
  - windows

compiler:
    - gcc
    - clang

  env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

  script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - ../bin/RedTextApplication
    
